# Project 1 - Web Scraping with Pandas

In [1]:
import numpy as np
import pandas as pd

In [2]:
#read 1 csv file form website
df_EPL = pd.read_csv('https://www.football-data.co.uk/mmz4281/2526/E0.csv')

In [3]:
df_EPL.head()

,Div,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [4]:
df_EPL.rename(columns={'FTHG':'home_goals','FTAG':'away_goals'},inplace=True)
df_EPL.head()

,Div,Date,Time,HomeTeam,AwayTeam,home_goals,away_goals,FTR,HTHG,HTAG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,E0,15/08/2025,20:00,Liverpool,Bournemouth,4,2,H,1,0,...,2.03,1.78,2.07,1.85,2.03,1.88,1.94,1.76,2.14,1.86
1,E0,16/08/2025,12:30,Aston Villa,Newcastle,0,0,D,0,0,...,2.05,1.80,2.02,1.89,2.06,1.80,1.95,1.74,2.14,1.86
2,E0,16/08/2025,15:00,Brighton,Fulham,1,1,D,0,0,...,1.83,2.03,1.93,2.00,1.84,2.03,1.80,1.96,1.91,2.08
3,E0,16/08/2025,15:00,Sunderland,West Ham,3,0,H,0,0,...,1.95,1.90,1.97,1.95,1.95,1.94,1.86,1.78,2.02,1.97
4,E0,16/08/2025,15:00,Tottenham,Burnley,3,0,H,1,0,...,1.98,1.88,1.99,1.93,1.98,1.91,1.88,1.83,2.07,1.92

In [ ]:
#Read CSV Files from multiple URLs
"https://www.football-data.co.uk/mmz4281/" + "2526" + "/" + "E0" + ".csv"

In [5]:
#Multiple Leagues
root="https://www.football-data.co.uk/mmz4281/"
leagues=['E0','E1','E2','E3','EC']

In [6]:
frames=[]
for league in leagues:
  df = pd.read_csv(root+ '2526' + '/' + league + '.csv')
  frames.append(df)

In [7]:
#Multiple Seasons
root="https://www.football-data.co.uk/mmz4281/"
leagues=['E0','E1','EC']

frames=[]
for league in leagues:
  for season in range(21,26):
    df = pd.read_csv(root+ str(season)+str(season+1) + '/' + league + '.csv',encoding='unicode_escape')
    df.insert(1,'Season',season)
    frames.append(df)

/tmp/ipykernel_3533/1200184761.py:9: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1,'Season',season)

In [8]:
len(frames)
frames[14]

,ï»¿Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,B365CAHH,B365CAHA,PCAHH,PCAHA,MaxCAHH,MaxCAHA,AvgCAHH,AvgCAHA,BFECAHH,BFECAHA
0,EC,25,09/08/2025,15:00,Altrincham,Aldershot,3,2,H,2,...,1.90,1.90,1.92,1.93,1.90,1.90,1.86,1.84,2.00,1.99
1,EC,25,09/08/2025,15:00,Boreham Wood,Rochdale,0,2,A,0,...,2.00,1.80,2.05,1.82,2.02,1.80,1.96,1.75,2.06,1.89
2,EC,25,09/08/2025,15:00,Brackley Town,Eastleigh,1,0,H,1,...,2.00,1.80,2.14,1.72,2.03,1.80,1.96,1.75,2.06,1.84
3,EC,25,09/08/2025,15:00,Braintree Town,Halifax,3,0,H,2,...,1.93,1.88,1.97,1.88,1.93,1.88,1.88,1.82,1.97,1.98
4,EC,25,09/08/2025,15:00,Gateshead,Southend,0,3,A,0,...,1.83,1.98,1.67,2.19,1.83,2.04,1.75,1.96,1.84,2.12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
535,EC,25,18/04/2026,15:00,Truro,Carlisle,0,1,A,0,...,2.08,1.73,NaN,NaN,2.08,1.73,2.00,1.70,2.24,1.75
536,EC,25,18/04/2026,15:00,Wealdstone,Scunthorpe,1,1,D,0,...,1.90,1.90,NaN,NaN,1.90,1.90,1.83,1.85,1.93,2.02
537,EC,25,18/04/2026,17:30,Braintree Town,Rochdale,1,2,A,0,...,1.90,1.90,NaN,NaN,1.90,1.90,1.83,1.85,1.88,1.98
538,EC,25,18/04/2026,17:30,York,Yeovil,3,0,H,2,...,1.90,1.90,NaN,NaN,1.90,1.90,1.84,1.84,1.92,1.95
539,EC,25,21/04/2026,19:45,Hartlepool,Southend,4,3,H,1,...,1.85,1.95,NaN,NaN,1.90,1.95,1.85,1.83,NaN,NaN

In [9]:
# Organize All the data in dictionary
dict_league={
    'Spanish La Liga':'SP1',
    'Spanish Seguda Division': 'SP2',
    'German Bundesliga': 'D1',
    'English Premier League': 'E0',
    'English League 1':'E1'
}

In [10]:
dict_historical_data={}


#Multiple Seasons
root="https://www.football-data.co.uk/mmz4281/"
#leagues=['E0','E1','EC']

for league in dict_league:
  frames=[]
  for season in range(20,26):
    df = pd.read_csv(root+ str(season)+str(season+1) + '/' + dict_league[league] + '.csv',encoding='unicode_escape')
    df.insert(1,'Season',season)
    frames.append(df)
  df_concat = pd.concat(frames)
  dict_historical_data[league]=df_concat

/tmp/ipykernel_3533/3851419048.py:12: PerformanceWarning: DataFrame is highly fragmented.  This is usually the result of calling `frame.insert` many times, which has poor performance.  Consider joining all columns at once using pd.concat(axis=1) instead. To get a de-fragmented frame, use `newframe = frame.copy()`
  df.insert(1,'Season',season)

In [11]:
dict_historical_data.keys()

dict_keys(['Spanish La Liga', 'Spanish Seguda Division', 'German Bundesliga', 'English Premier League', 'English League 1'])

In [12]:
dict_historical_data['Spanish La Liga']

,Div,Season,Date,Time,HomeTeam,AwayTeam,FTHG,FTAG,FTR,HTHG,...,BMGMCA,BVCH,BVCD,BVCA,CLCH,CLCD,CLCA,LBCH,LBCD,LBCA
0,SP1,20,12/09/2020,15:00,Eibar,Celta,0,0,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,SP1,20,12/09/2020,17:30,Granada,Ath Bilbao,2,0,H,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,SP1,20,12/09/2020,20:00,Cadiz,Osasuna,0,2,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,SP1,20,13/09/2020,13:00,Alaves,Betis,0,1,A,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,SP1,20,13/09/2020,15:00,Valladolid,Sociedad,1,1,D,1,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,NaN,25,22/04/2026,19:00,Sociedad,Getafe,0,1,A,0,...,3.60,2.25,3.13,3.4,2.25,3.0,3.5,2.25,3.0,3.5
316,NaN,25,22/04/2026,20:30,Barcelona,Celta,1,0,H,1,...,10.50,1.22,7.00,11.0,1.25,7.0,9.0,1.25,7.0,8.5
317,NaN,25,23/04/2026,18:00,Levante,Sevilla,2,0,H,1,...,2.95,2.45,3.10,3.1,2.40,3.2,3.0,2.40,3.2,3.0
318,NaN,25,23/04/2026,19:00,Vallecano,Espanol,1,0,H,0,...,3.75,2.10,3.30,3.6,2.10,3.3,3.5,2.10,3.3,3.5
319,NaN,25,23/04/2026,20:30,Oviedo,Villarreal,1,1,D,0,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN