In [2]:
import pandas as pd
import numpy as np

In [3]:
df_laptops=pd.read_csv('laptops.csv')
df_laptops.head(3)

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.0
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.0
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.0

In [4]:
#Find rows which have 'Apple' in the 'Brand' column
df_laptops['Brand']=='Asus'

#Filter Dataframe based on condition
df_laptops[df_laptops['Brand']=='Asus'].value_counts('Brand')

Brand
Asus    415
Name: count, dtype: int64

In [5]:
#EXERCISE 1:
#Find rows which dont have 'HP' in the 'Brand' column
df_laptops['Brand']!='HP'

#Filter dataframe based on condition
df_laptops[df_laptops['Brand']!='HP'].value_counts('Brand')

Brand
Asus                415
Lenovo              366
MSI                 308
Acer                137
Apple               116
Dell                 84
Microsoft            77
Gigabyte             48
Razer                37
Medion               32
LG                   32
Alurin               29
PcCom                24
Samsung              22
Dynabook Toshiba     19
Vant                 11
Primux                8
Deep Gaming           8
Innjoo                6
Thomson               4
Prixton               3
Millenium             2
Denver                1
Jetwing               1
Realme                1
Toshiba               1
Name: count, dtype: int64

In [6]:
#EXERCISE 2:
#Find laptops with Final Price over 2000

df_laptops[df_laptops['Final Price'] > 2000].value_counts('Brand')

Brand
MSI          105
Asus          69
Lenovo        38
Razer         32
Apple         26
Microsoft     20
HP            19
Gigabyte      14
Acer          11
Dell           9
LG             8
Samsung        6
Medion         3
Millenium      1
Name: count, dtype: int64

# Create a Column Based on 1 Condition: np.where()

In [7]:
#create an array based on price tiers
#np.where(df_laptops['Final Price']>2000,'Expensive','Cheap')

#Set it into a new Column
df_laptops['Price Tier'] = np.where(df_laptops['Final Price']>2000,'Expensive','Cheap')
df_laptops.value_counts('Price Tier')
df_laptops.head()

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,Price Tier
0,ASUS ExpertBook B1 B1502CBA-EJ0436X Intel Core...,New,Asus,ExpertBook,Intel Core i5,8,512,SSD,NaN,15.6,No,1009.00,Cheap
1,Alurin Go Start Intel Celeron N4020/8GB/256GB ...,New,Alurin,Go,Intel Celeron,8,256,SSD,NaN,15.6,No,299.00,Cheap
2,ASUS ExpertBook B1 B1502CBA-EJ0424X Intel Core...,New,Asus,ExpertBook,Intel Core i3,8,256,SSD,NaN,15.6,No,789.00,Cheap
3,MSI Katana GF66 12UC-082XES Intel Core i7-1270...,New,MSI,Katana,Intel Core i7,16,1000,SSD,RTX 3050,15.6,No,1199.00,Cheap
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01,Cheap

In [8]:
#EXERCISE 1
#create an array based on Screen
#np.where(df_laptops['Screen']>14.0,'Big','Small')

df_laptops['Screen Size']=np.where(df_laptops['Screen']>14.0,'Big','Small')
df_laptops.value_counts('Screen Size')

Screen Size
Big      1506
Small     654
Name: count, dtype: int64

# Filer dataframe based on multiple conditions

In [9]:
#Find Apple laptops that costs more than 2000
(df_laptops['Brand']=='Apple') & (df_laptops['Final Price']>2000)


df_laptops[(df_laptops['Brand']=='Apple') & (df_laptops['Final Price']>2000)]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,Price Tier,Screen Size
295,Apple MacBook Pro Apple M2 Pro 10 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,14.2,No,2209.00,Expensive,Big
360,Apple MacBook Pro Apple M2 Pro 10 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,14.2,No,2269.00,Expensive,Big
416,Apple MacBook Pro Apple M1 Max/32GB/1TB SSD/16...,New,Apple,MacBook Pro,Apple M1,32,1000,SSD,NaN,16.2,No,3849.00,Expensive,Big
500,Apple MacBook Pro Apple M2 Max/32GB/1TB SSD/16...,New,Apple,MacBook Pro,Apple M2,32,1000,SSD,NaN,16.2,No,3799.00,Expensive,Big
501,Apple MacBook Pro Apple M2 Max/32GB/1TB SSD/14...,New,Apple,MacBook Pro,Apple M2,32,1000,SSD,NaN,14.2,No,3379.01,Expensive,Big
510,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,14.2,No,2729.01,Expensive,Big
532,Apple MacBook Pro Apple M2 Pro 10 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,512,SSD,NaN,14.2,No,2719.00,Expensive,Big
538,Apple MacBook Pro Apple M2 Pro 10 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,1000,SSD,NaN,14.2,No,2939.01,Expensive,Big
556,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,16.2,No,2729.01,Expensive,Big
583,Apple MacBook Pro Apple M2 Pro 12 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,1000,SSD,NaN,16.2,No,3499.01,Expensive,Big
631,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,16.2,No,2999.01,Expensive,Big
665,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,14.2,No,2749.00,Expensive,Big
667,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,16.2,No,2789.00,Expensive,Big
683,Apple MacBook Pro Apple M2 Max/32GB/1TB SSD/14...,New,Apple,MacBook Pro,Apple M2,32,1000,SSD,NaN,14.2,No,3399.00,Expensive,Big
725,Apple MacBook Pro Apple M2 Pro 12 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,1000,SSD,NaN,14.2,No,3279.00,Expensive,Big
742,Apple MacBook Pro Apple M2 Pro 12 Núcleos/32GB...,New,Apple,MacBook Pro,Apple M2 Pro,32,512,SSD,NaN,16.2,No,3279.00,Expensive,Big
870,Apple MacBook Pro Apple M2 Pro 12 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,1000,SSD,NaN,16.2,No,2999.01,Expensive,Big
1026,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/14...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,14.2,No,2749.00,Expensive,Big
1052,Apple Macbook Pro Intel Core i9/32GB/2TB SSD/R...,Refurbished,Apple,MacBook Pro,Intel Core i9,32,2000,SSD,Radeon Pro 5500M,16.0,No,2755.00,Expensive,Big
1133,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/14...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,14.2,No,2749.00,Expensive,Big
1744,Apple MacBook Pro 2021 Apple M1 Pro/16GB/1TB S...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,14.2,No,2500.01,Expensive,Big
1745,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/16...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,16.2,No,2979.00,Expensive,Big
1746,Apple MacBook Pro Apple M1 Pro/16GB/1TB SSD/16...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,1000,SSD,NaN,16.2,No,2950.00,Expensive,Big
1747,Apple MacBook Pro Apple M1 Pro/16GB/512GB SSD/...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,16,512,SSD,NaN,14.2,No,2500.01,Expensive,Big
1748,Apple MacBook Pro Apple M1 Pro/32GB/1TB SSD/14...,Refurbished,Apple,MacBook Pro,Apple M1 Pro,32,1000,SSD,NaN,14.2,No,2500.01,Expensive,Big
1770,Apple Macbook Pro Intel Core i9/32GB/2TB SSD/R...,Refurbished,Apple,MacBook Pro,Intel Core i9,32,2000,SSD,Radeon Pro 5500M,16.0,No,2711.40,Expensive,Big

In [10]:
#Apple or Dell laptops
df_laptops[(df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')]
df_laptops[(df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')].value_counts('Brand')

Brand
Apple    116
Dell      84
Name: count, dtype: int64

In [11]:
#Laptop from Apple or Dell that costs over 2000
df_laptops[((df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')) & (df_laptops['Final Price']>2000)]
df_laptops[((df_laptops['Brand']=='Apple') | (df_laptops['Brand']=='Dell')) & (df_laptops['Final Price']>2000)].value_counts('Brand')

Brand
Apple    26
Dell      9
Name: count, dtype: int64

# Creating a conditional column from more than 2 choices: np.select()

In [12]:
#create an array based on multiple price tiers
#create conditions and values variable
conditions=[
    df_laptops['Final Price']>3000,
    (df_laptops['Final Price']>2000) & (df_laptops['Final Price']<=3000),
    (df_laptops['Final Price']>800) & (df_laptops['Final Price']<=2000),
    (df_laptops['Final Price']<=800)            
]

values=['Elite','Expensive','Budget','Cheap']

#set it to a new column
#np.select(conditions,values,default='Unknown')
df_laptops['Price Tier']=np.select(conditions,values,default='Unknown')

#show dataframe
df_laptops.head()

#count values inside price tier column
df_laptops.value_counts('Price Tier')
df_laptops['Price Tier'].value_counts()

df_laptops.head()
df_laptops['Screen'].value_counts()

Screen
15.60    1009
14.00     392
16.00     174
17.30     161
13.30     131
16.10      48
17.00      33
13.00      27
15.00      21
13.40      19
13.50      19
11.60      16
14.20      14
12.30      13
13.60      11
14.10      11
16.20      10
15.30       8
10.50       7
12.40       6
14.40       6
15.40       5
12.00       4
14.50       3
18.00       3
13.90       2
12.50       1
10.10       1
10.95       1
Name: count, dtype: int64

In [ ]:
#EXERCISE 
#create an array based on mutliple screen tiers -> too big, big, small, too small

#create conditions and values variable
conditions=[ 
    (df_laptops['Screen']>16.0),
    (df_laptops['Screen']>14.0) & (df_laptops['Screen']<=16.0),
    (df_laptops['Screen']>12.0) & (df_laptops['Screen']<=14.0),
    (df_laptops['Screen']<=12.0)
]

values=['Large','Big','Regular','Small']

df_laptops['Screen Size']=np.select(conditions,values,default='UA')
#show dataframe
df_laptops.head()

#count values inside screen size column
df_laptops.value_counts('Screen Size')

Screen Size
Big        1251
Regular     621
Large       255
Small        29
UA            4
Name: count, dtype: int64

# isin()

In [15]:
# isin() : Single Filtering

#select Apple or HP laptops
df_laptops['Brand'].isin(['Apple','HP'])


df_laptops[df_laptops['Brand'].isin(['Apple','HP'])].value_counts('Brand')
df_laptops[df_laptops['Brand'].isin(['Apple','HP'])]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,Price Tier,Screen Size
4,HP 15S-FQ5085NS Intel Core i5-1235U/16GB/512GB...,New,HP,15S,Intel Core i5,16,512,SSD,NaN,15.6,No,669.01,Cheap,Big
9,HP Victus 16-d1038ns Intel Core i7-12700H/16GB...,New,HP,Victus,Intel Core i7,16,512,SSD,RTX 3050,16.1,No,1149.00,Budget,Large
15,HP 15S-FQ5013NS Intel Core i5-1235U/8GB/512GB ...,New,HP,15S,Intel Core i5,8,512,SSD,NaN,15.6,No,699.00,Cheap,Big
17,HP 15S-FQ2163NS Intel Core i3-1115G4/8GB/512GB...,New,HP,15S,Intel Core i3,8,512,SSD,NaN,15.6,No,549.00,Cheap,Big
27,HP Victus 15-fa0012ns Intel Core i5-12500H/16G...,New,HP,Victus,Intel Core i5,16,512,SSD,RTX 3050,15.6,No,999.00,Budget,Big
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1921,HP Victus 16-e0030ns AMD Ryzen 5 5600H/16GB/51...,Refurbished,HP,Victus,AMD Ryzen 5,16,512,SSD,RTX 3050,16.1,No,735.84,Cheap,Large
1922,HP ZBook Firefly 14 G8 Intel Core i7-1165G7/16...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,NaN,14.0,No,1619.46,Budget,Regular
1923,HP ZBook Firefly 15 G8 Intel Core i7-1165G7/16...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,T 500,15.6,No,2677.83,Expensive,Big
1924,HP ZBook Fury G8 Intel Core i7-11800H/16 GB/51...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,RTX A3000,15.6,No,3848.01,Elite,Big
1925,HP ZBook Fury G8 Intel Core i9-11900H/32GB/1TB...,Refurbished,HP,Zbook,Intel Core i9,32,1000,SSD,NaN,15.6,No,4805.65,Elite,Big

In [16]:
# isin() : Multiple Filtering

#find MacBook Pro or Zbook from Apple or HP
filter1=df_laptops['Model'].isin(['MacBook Pro','Zbook'])
filter2=df_laptops['Brand'].isin(['Apple','HP'])

df_laptops[filter1 & filter2]

,Laptop,Status,Brand,Model,CPU,RAM,Storage,Storage type,GPU,Screen,Touch,Final Price,Price Tier,Screen Size
69,Apple Macbook Pro Apple M2/8GB/256GB SSD/GPU D...,New,Apple,MacBook Pro,Apple M2,8,256,SSD,NaN,13.3,No,1599.00,Budget,Regular
240,Apple Macbook Pro Apple M2/8GB/256GB SSD/GPU D...,New,Apple,MacBook Pro,Apple M2,8,256,SSD,NaN,13.3,No,1619.00,Budget,Regular
295,Apple MacBook Pro Apple M2 Pro 10 Núcleos/16GB...,New,Apple,MacBook Pro,Apple M2 Pro,16,512,SSD,NaN,14.2,No,2209.00,Expensive,Big
341,Apple Macbook Pro Apple M2/8GB/512GB SSD/GPU D...,New,Apple,MacBook Pro,Apple M2,8,512,SSD,NaN,13.3,No,1849.00,Budget,Regular
342,Apple Macbook Pro Apple M2/16GB/256GB SSD/GPU ...,New,Apple,MacBook Pro,Apple M2,16,256,SSD,NaN,13.3,No,1729.01,Budget,Regular
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1770,Apple Macbook Pro Intel Core i9/32GB/2TB SSD/R...,Refurbished,Apple,MacBook Pro,Intel Core i9,32,2000,SSD,Radeon Pro 5500M,16.0,No,2711.40,Expensive,Big
1922,HP ZBook Firefly 14 G8 Intel Core i7-1165G7/16...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,NaN,14.0,No,1619.46,Budget,Regular
1923,HP ZBook Firefly 15 G8 Intel Core i7-1165G7/16...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,T 500,15.6,No,2677.83,Expensive,Big
1924,HP ZBook Fury G8 Intel Core i7-11800H/16 GB/51...,Refurbished,HP,Zbook,Intel Core i7,16,512,SSD,RTX A3000,15.6,No,3848.01,Elite,Big
1925,HP ZBook Fury G8 Intel Core i9-11900H/32GB/1TB...,Refurbished,HP,Zbook,Intel Core i9,32,1000,SSD,NaN,15.6,No,4805.65,Elite,Big